### ISSUE TITLE
Error when incoming message is empty

### ISSUE THREAD

**Issue by jroper** [lightbend/akkaserverless-javascript-sdk#171]
If the incoming message is empty, for example, if you create an action service and the request message is `google.protobuf.Empty`, Node will crash with the following output when you attempt to invoke it:

```
/home/jroper/src/akkaserverless-javascript-sdk/sdk/node_modules/protobufjs/src/reader.js:47
        throw Error("illegal buffer");
        ^

Error: illegal buffer
    at create_typed_array (/home/jroper/src/akkaserverless-javascript-sdk/sdk/node_modules/protobufjs/src/reader.js:47:15)
    at Function.create_buffer [as create] (/home/jroper/src/akkaserverless-javascript-sdk/sdk/node_modules/protobufjs/src/reader.js:63:23)
    at Type.GetMyFriendsRequest$decode [as decode] (eval at Codegen (/home/jroper/src/akkaserverless-javascript-sdk/sdk/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:5:12)
    at Type.decode_setup [as decode] (/home/jroper/src/akkaserverless-javascript-sdk/sdk/node_modules/protobufjs/src/type.js:507:25)
    at AnySupport.deserialize (/home/jroper/src/akkaserverless-javascript-sdk/sdk/src/protobuf-any.js:231:17)
    at ActionHandler.handleUnary (/home/jroper/src/akkaserverless-javascript-sdk/sdk/src/action-support.js:178:57)
    at ActionServices.handleUnary (/home/jroper/src/akkaserverless-javascript-sdk/sdk/src/action-support.js:598:15)
    at /home/jroper/src/akkaserverless-javascript-sdk/sdk/node_modules/grpc/src/server.js:594:13
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jwt-test@0.0.1 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jwt-test@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jroper/.npm/_logs/2021-09-08T08_49_54_244Z-debug.log
```

**Comment by jroper** [comment]
Turns out I was using an old version of the SDK and it's already fixed.
