### ISSUE TITLE
[create-akkasls-entity] Containerization is failing for newly generated projects

### ISSUE THREAD

**Issue by janory** [lightbend/akkaserverless-javascript-sdk#73]
## Summary
I came across with some issues when I tried to package a newly created project with the `create-akkasls-entity` tool.

#### Steps to reproduce:
```
npx @lightbend/create-akkasls-entity my-first-service
cd my-first-service
npm i
npm run build
npm run package
```

#### Environment:
```
node: v15.10.0
npm: 7.5.3
```

## Issue 1: 
Protobuf tries to install some missing packages during runtime, which leads to errors in a Docker environment, probably due to lack of permissions.

#### Stacktrace:
```
lightbend/akkaserverless-codegen#12 1.012 Error: Command failed: npm --silent install jsdoc@^3.6.3 uglify-js@^3.7.7
lightbend/akkaserverless-codegen#12 1.012     at checkExecSyncError (node:child_process:680:11)
lightbend/akkaserverless-codegen#12 1.012     at Object.execSync (node:child_process:717:15)
lightbend/akkaserverless-codegen#12 1.012     at modInstall (/home/node/node_modules/protobufjs/cli/util.js:129:19)
lightbend/akkaserverless-codegen#12 1.012     at Object.exports.setup (/home/node/node_modules/protobufjs/cli/util.js:156:5)
lightbend/akkaserverless-codegen#12 1.012     at Object.<anonymous> (/home/node/node_modules/protobufjs/cli/pbjs.js:7:6)
lightbend/akkaserverless-codegen#12 1.012     at Module._compile (node:internal/modules/cjs/loader:1091:14)
lightbend/akkaserverless-codegen#12 1.012     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
lightbend/akkaserverless-codegen#12 1.012     at Module.load (node:internal/modules/cjs/loader:971:32)
lightbend/akkaserverless-codegen#12 1.012     at Function.Module._load (node:internal/modules/cjs/loader:812:14)
lightbend/akkaserverless-codegen#12 1.012     at Module.require (node:internal/modules/cjs/loader:995:19) {
```

#### More info: 
https://github.com/protobufjs/protobuf.js/issues/1368
https://github.com/protobufjs/protobuf.js/pull/1234

#### Solution:
This issue will be fixed in pb version 7, in the meanwhile we would need to add the following deps as the `devDependencies`:
```
    "jsdoc": "^3.6.3",
    "uglify-js": "^3.7.7"
```
This way `npm ci` will install these deps and pb won't try to install them during runtime.

**Comment by ennru** [comment]
Closing historic issue.
