### ISSUE TITLE
serializeFallbackToJson not working as expected

### ISSUE THREAD

**Issue by retgits** [lightbend/akkaserverless-javascript-sdk#84]
I've created a Value Entity in JavaScript using:

```javascript
const entity = new as.ValueEntity(
    ['valueentity.proto',],
    'valueentity.valueEntityService',
    'valueentities',
    {
        serializeFallbackToJson: true
    }
);
```

and the command handler being

```javascript
function sayHelloWorld(request, current, context) {
    let message = { message: `${request.greeting}, ${request.name}!` };

    context.updateState({
        name: context.entityId,
        message: `${request.greeting}, ${request.name}!`
    })

    return message;
}
```

When I run that application and send a message, it throws an error

```
Error: Fallback to JSON serialization supported, but object does not define a type property: { name: 'leon', message: 'hello, leon!' }
    at Function.serialize (/home/node/node_modules/@lightbend/akkaserverless-javascript-sdk/dist/src/protobuf-any.js:199:27)
    at ValueEntitySupport.serialize (/home/node/node_modules/@lightbend/akkaserverless-javascript-sdk/dist/src/value-entity-support.js:40:27)
    at Object.ctx.context.updateState (/home/node/node_modules/@lightbend/akkaserverless-javascript-sdk/dist/src/value-entity-support.js:112:55)
    at Object.sayHelloWorld [as SayHello] (file:///home/node/valueentity.js:70:13)
    at ValueEntityHandler.<anonymous> (/home/node/node_modules/@lightbend/akkaserverless-javascript-sdk/dist/src/value-entity-support.js:123:85)
    at Generator.next (<anonymous>)
    at /home/node/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/node/node_modules/tslib/tslib.js:113:16)
    at /home/node/node_modules/@lightbend/akkaserverless-javascript-sdk/dist/src/value-entity-support.js:88:50
```

Surprisingly when I update the message itself to add a `type` field, it works perfectly

```json
{
  type: 'object'
  name: context.entityId,
  message: `${request.greeting}, ${request.name}!`
}
```

This is also likely the cause of https://discuss.lightbend.com/t/error-fallback-to-json-serialization-supported-but-object-does-not-define-a-type-property/8441/3

**Comment by retgits** [comment]
After reading the source code I see that this is expected behavior... closing this issue for now

**Comment by pvlugter** [comment]
Yes, this is expected currently. As far as I know, the `type` field in JSON-serialized events for event sourced entities is only used to determine which event handler should be called. This probably doesn't make sense to also require for value entity state. I'll reopen so we can follow up on this.
